<Workspace Version="1.3.4.6666" X="-280.967276858415" Y="265.743005781289" zoom="1.16438980805626" ScaleFactor="1" Name="3DView by BoundingBox" Description="Use a boundingbox to create a new 3D View with a specified name.&#xD;&#xA;Note: Use the &quot;Remove Special Characters from String&quot; node to obtain a view name without prohibited characters." ID="42548128-8606-41a0-920b-3cfa3a66d961" Category="GeniusLoci.View">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1f37198f-21bd-4b82-805e-fb8b8022b4ac" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="250.705708561732" y="13.8975315705315" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Future Section box&#xD;&#xA;boundingBox" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c965bdcc-3e5f-4590-8a09-6aba97526350" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="665.115303176804" y="44.9801991454159" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="def2cd54-e3cb-400d-9a4d-2919d36027e5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="326.086828276943" y="100.453846562683" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="viewName" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="9a773cf9-4f25-44fd-86b7-a2812569fbad" type="PythonNodeModels.PythonNode" nickname="Python Script" x="493.462008990311" y="37.7996033682453" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

def tolist(obj1):
    if hasattr(obj1,"__iter__"): return obj1
    else: return [obj1]

bboxs = tolist(IN[0])
viewNames = tolist(IN[1])
views=[]

#Get 3D View ViewFamilyType
viewTypeColl = FilteredElementCollector(doc).OfClass(ViewFamilyType)
for i in viewTypeColl:
	if i.ViewFamily == ViewFamily.ThreeDimensional:
		viewType = i
	else:
		continue

for bbox,viewName in zip(bboxs,viewNames):
	newmax = UnwrapElement(bbox.MaxPoint).ToRevitType()
	newmin = UnwrapElement(bbox.MinPoint).ToRevitType()
	newbox = BoundingBoxXYZ()
	newbox.Max = newmax
	newbox.Min = newmin
	try:
		TransactionManager.Instance.EnsureInTransaction(doc)
		view = View3D.CreateIsometric(doc, viewType.Id)
		view.Name = viewName
		view.SetSectionBox(newbox)
		views.append(view)
		TransactionManager.Instance.TransactionTaskDone()
	except Exception, ex:
		views.append(ex.message)

OUT = views</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1f37198f-21bd-4b82-805e-fb8b8022b4ac" start_index="0" end="9a773cf9-4f25-44fd-86b7-a2812569fbad" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="def2cd54-e3cb-400d-9a4d-2919d36027e5" start_index="0" end="9a773cf9-4f25-44fd-86b7-a2812569fbad" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9a773cf9-4f25-44fd-86b7-a2812569fbad" start_index="0" end="c965bdcc-3e5f-4590-8a09-6aba97526350" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>