<Workspace Version="1.3.4.6666" X="-122.248005375174" Y="19.3513091773485" zoom="0.803321593462598" ScaleFactor="1" Name="All Elements of Family" Description="Get the family instances of the given loadable family." ID="fd943c39-2c51-45b6-b7e6-8a35d39a7859" Category="GeniusLoci.Family">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="567dd79c-8f37-404b-8cfd-18b59a058880" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="637.8" y="276" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="1645cd79-7ef5-411b-a5a9-a6bd0b455515" type="PythonNodeModels.PythonNode" nickname="Python Script" x="413.4" y="276" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2020
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import FilteredElementCollector

families = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]

instances=[FilteredElementCollector(fam.Document).OfCategoryId(fam.FamilyCategoryId).WhereElementIsNotElementType().ToElements().FindAll(lambda x : fam.Document.GetElement(x.GetTypeId()).Family.Id == fam.Id) for fam in families]

if isinstance(IN[0], list): OUT = instances
else: OUT = instances[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="de0eb6b4-f652-4e91-8be4-36363de798ed" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="233.4" y="276" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="family" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1645cd79-7ef5-411b-a5a9-a6bd0b455515" start_index="0" end="567dd79c-8f37-404b-8cfd-18b59a058880" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="de0eb6b4-f652-4e91-8be4-36363de798ed" start_index="0" end="1645cd79-7ef5-411b-a5a9-a6bd0b455515" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>