<Workspace Version="1.3.4.6666" X="277.337161983908" Y="139.946231930597" zoom="0.415702480451715" ScaleFactor="1" Name="CAD Block" Description="Get the location point, name and layer of the CAD blocks / XRefs from a CAD link or import." ID="3a5e2f99-da0a-4d0b-a193-42619cb76458" Category="GeniusLoci.CAD Import">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ae971eec-a1dc-4577-9ccb-a60a6ec5af94" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="244.703711927053" y="214.862102804032" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];&#xA;x[2];&#xA;x[3];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="72fb619b-585a-491c-97a4-8c6f686b796d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="20.3037119270531" y="210.648769470699" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2021
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo
  
import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import Options,GeometryInstance, XYZ
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)
import math

points,rotations,blocks,layersAll=[],[],[],[]

elem = UnwrapElement(IN[0])
geoElem = elem.get_Geometry(Options())		
for geoObj in geoElem:
	transform=geoObj.Transform
	instance=geoObj.SymbolGeometry
	for inst in instance:
		layers=[]
		if isinstance(inst,GeometryInstance):
			points.append(transform.OfPoint(inst.Transform.Origin).ToPoint())
			rotation=abs(math.degrees(inst.Transform.BasisX.AngleOnPlaneTo(XYZ.BasisX, XYZ.BasisZ))-360)
			if round(rotation,3)==360:
				rotation = 0
			rotations.append(round(rotation,3))
			blocks.append(inst.Symbol.ToDSType(True).Name.split(".dwg.")[-1])
			geom=inst.SymbolGeometry
			for geo in geom:
				try:
					layers.append(elem.Document.GetElement(geo.GraphicsStyleId).GraphicsStyleCategory.Name)
				except:
					pass
			layersAll.append(layers[0])
			
OUT = blocks,points,rotations,layersAll</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3a8d25d5-80eb-4c97-8687-5087a670edde" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="435.903711927053" y="145.222102804032" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="BlockName" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6389816b-f44a-44d7-9341-db6d83e3be23" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="435.903711927053" y="228.222102804032" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OriginPoint" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b4b3400b-7471-4597-8731-e366a3ac0d63" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="435.903711927053" y="311.222102804032" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Rotation" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bcd39bc3-f546-4fdb-ae92-77d7c7f138cb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-275.296288072947" y="210.648769470699" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="importInstance:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6af00135-eb3d-4d9d-93a5-9519411eb5eb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="431.598088664746" y="393.529599248015" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="LayerName" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ae971eec-a1dc-4577-9ccb-a60a6ec5af94" start_index="0" end="3a8d25d5-80eb-4c97-8687-5087a670edde" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ae971eec-a1dc-4577-9ccb-a60a6ec5af94" start_index="1" end="6389816b-f44a-44d7-9341-db6d83e3be23" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ae971eec-a1dc-4577-9ccb-a60a6ec5af94" start_index="2" end="b4b3400b-7471-4597-8731-e366a3ac0d63" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ae971eec-a1dc-4577-9ccb-a60a6ec5af94" start_index="3" end="6af00135-eb3d-4d9d-93a5-9519411eb5eb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="72fb619b-585a-491c-97a4-8c6f686b796d" start_index="0" end="ae971eec-a1dc-4577-9ccb-a60a6ec5af94" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bcd39bc3-f546-4fdb-ae92-77d7c7f138cb" start_index="0" end="72fb619b-585a-491c-97a4-8c6f686b796d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>