<Workspace Version="1.3.4.6666" X="-56.3404241273162" Y="43.2705231666367" zoom="0.729950825270786" ScaleFactor="1" Name="Collector of Detail Items Types" Description="Retrieves all the Detail Items Family Types in the model." ID="39264f65-8f63-45f1-9800-d8cb5e00d0d0" Category="GeniusLoci.Select">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9af9a205-197e-459a-8e93-c61dd54fdfd4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="219.443655517556" y="296.43922456991" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="refresh:bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="25cd595e-dca6-4151-aba9-1669102b370f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="622" y="294.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Detail Items Types" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="9f58b545-8cad-424c-8cce-56a4f3a433e4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="445.430188300833" y="301.838411196321" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

familyTypes = FilteredElementCollector(doc).OfClass(Autodesk.Revit.DB.FamilySymbol).ToElements()

detaiItems=[]

for x in familyTypes :
	if x.Category.Id == ElementId(BuiltInCategory.OST_DetailComponents):
		detaiItems.append(x)

OUT=detaiItems</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9af9a205-197e-459a-8e93-c61dd54fdfd4" start_index="0" end="9f58b545-8cad-424c-8cce-56a4f3a433e4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f58b545-8cad-424c-8cce-56a4f3a433e4" start_index="0" end="25cd595e-dca6-4151-aba9-1669102b370f" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>