<Workspace Version="1.3.4.6666" X="-46.2982001923039" Y="211.877251916764" zoom="0.496674521251666" ScaleFactor="1" Name="Create Legend Component" Description="Inserts a new legend component by duplicating an existing in the given legend view.&#xD;&#xA;Please note : At least one legend component must be placed in the legend view." ID="bee2d6eb-0fe2-4761-99a8-33ef35b8be26" Category="GeniusLoci.Element">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Elements.Views.View3D" resolvedName="Revit.Elements.Views.View3D" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Revit.Elements.Views.View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Elements.LegendView" resolvedName="Prorubim.Common.Revit.Elements.LegendView" assemblyName="ProrubimCommonKit.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8b13d9f8-c092-4900-8ad9-def366ff24bc" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1111.67531942083" y="17.3744447670765" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Legend Component" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="464e319f-292c-4e70-b340-4967125a2f52" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="327.67531942083" y="-46.6255552329235" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Legend view&#xD;&#xA;view" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="675d429c-6ef1-4dd2-92dd-e7722c926433" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="327.67531942083" y="46.3744447670765" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="familyType:var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0d99ca46-5764-4c4a-8603-dcfe75c432ff" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="245.52896752587" y="123.931593638061" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Point where the component is to be placed&#xD;&#xA;location: Autodesk.DesignScript.Geometry.Point[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="37e3c6ec-082e-430b-9122-6ec2f65b3687" type="PythonNodeModels.PythonNode" nickname="Python Script" x="886.87531942083" y="17.3744447670765" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Idea by Oliwer Kulpa : https://thebuildingcoder.typepad.com/blog/2010/05/duplicate-legend-component.html
import clr
# Import RevitAPI Classes
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

view = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
view=view[0]
family_types = UnwrapElement(IN[1]) if isinstance(IN[1],list) else [UnwrapElement(IN[1])]
translations = IN[2] if isinstance(IN[2],list) else [IN[2]]
output=[]

existing_legend_component = FilteredElementCollector(doc, view.Id).OfCategory(BuiltInCategory.OST_LegendComponents).FirstElement()
# Get the location of the existing_legend_component
box = existing_legend_component.BoundingBox[view]
mid = (box.Min+box.Max)/2

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)
for translation,family_type in zip(translations,family_types):
	# Copy the existing legend component at the correct location
	new_legend_component = ElementTransformUtils.CopyElement(doc, existing_legend_component.Id,translation.ToRevitType()-mid)
	# Change the family type of the new element
	doc.GetElement(new_legend_component[0]).get_Parameter(BuiltInParameter.LEGEND_COMPONENT).Set(family_type.Id)
	output.append(doc.GetElement(new_legend_component[0]))
doc.Regenerate()
# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT=output</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="464e319f-292c-4e70-b340-4967125a2f52" start_index="0" end="37e3c6ec-082e-430b-9122-6ec2f65b3687" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="675d429c-6ef1-4dd2-92dd-e7722c926433" start_index="0" end="37e3c6ec-082e-430b-9122-6ec2f65b3687" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0d99ca46-5764-4c4a-8603-dcfe75c432ff" start_index="0" end="37e3c6ec-082e-430b-9122-6ec2f65b3687" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="37e3c6ec-082e-430b-9122-6ec2f65b3687" start_index="0" end="8b13d9f8-c092-4900-8ad9-def366ff24bc" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>