<Workspace Version="1.3.4.6666" X="-276.743426128005" Y="-2.36724678114786" zoom="0.847618571998227" ScaleFactor="1" Name="Element Points References" Description="Returns the references to the start and the end points of the curve based element.&#xD;&#xA;(Works best with coarse detail level for cable trays and conduits categories)" ID="3f5fc3cf-0106-49f1-b938-cd0d43259a2c" Category="GeniusLoci.Reference">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c1956f4e-4e69-407f-a7f6-bb516caed3f9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="210.008073413106" y="296.814544345299" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Curve based element&#xD;&#xA;linearElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1c57042e-6b7c-4782-a4c7-514eb00edf59" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="929.208073413106" y="263.601211011966" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="References" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f1511df3-6f88-4ef1-916d-af36c1a4cb86" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="929.208073413106" y="347.601211011966" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Points" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="fd8e3213-76bd-4e5f-ba23-c6700577d262" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="738.008073413106" y="301.027877678633" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="40ccfb16-e8c6-4eb7-a7ef-a87c7a8f33c1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="513.608073413106" y="296.814544345299" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import Options,ReferenceArray,Line

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

items = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
	
allReferences,allPoints =[],[]

opt = Options()
opt.ComputeReferences = True
opt.IncludeNonVisibleObjects = True
opt.View = doc.ActiveView
for item in items:
	references = ReferenceArray()
	points=[]
	for obj in item.get_Geometry(opt):
		if isinstance(obj, Line):
			gline = obj
			references=gline.GetEndPointReference(0),gline.GetEndPointReference(1)
			points=gline.GetEndPoint(0).ToPoint(),gline.GetEndPoint(1).ToPoint()
	allReferences.append(references)
	allPoints.append(points)

if isinstance(IN[0], (list)): OUT = allReferences,allPoints
else: OUT = allReferences[0],allPoints[0]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c1956f4e-4e69-407f-a7f6-bb516caed3f9" start_index="0" end="40ccfb16-e8c6-4eb7-a7ef-a87c7a8f33c1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd8e3213-76bd-4e5f-ba23-c6700577d262" start_index="0" end="1c57042e-6b7c-4782-a4c7-514eb00edf59" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd8e3213-76bd-4e5f-ba23-c6700577d262" start_index="1" end="f1511df3-6f88-4ef1-916d-af36c1a4cb86" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="40ccfb16-e8c6-4eb7-a7ef-a87c7a8f33c1" start_index="0" end="fd8e3213-76bd-4e5f-ba23-c6700577d262" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>