<Workspace Version="1.3.4.6666" X="-136.676" Y="38.706" zoom="0.8425" ScaleFactor="1" Name="Element Origin Reference" Description="Retrieves the origin point of the family instance." ID="288f683f-0746-46c9-980b-b478ffb7d54a" Category="GeniusLoci.Reference">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7d3ac5db-f406-44c0-a98e-ecff5325141e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="176" y="265.613333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6c504b73-f7b8-4b18-b8c8-510f4ad83193" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="780" y="232.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Reference" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="aea22160-5352-44e1-b28e-f7f1aa6fdc90" type="PythonNodeModels.PythonNode" nickname="Python Script" x="364" y="265.613333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2020
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

items = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]

locationPoint,locRef = [],[]
refArr = ReferenceArray()

for item in items:
	refArr.Append(Reference.ParseFromStableRepresentation(doc, item.UniqueId + ":0:INSTANCE:" + item.Symbol.UniqueId + ":1:SURFACE"))
	location = item.Location
	if isinstance(location,LocationPoint):
		locationPoint.append(location.Point.ToPoint())
	else:
		locationPoint.append(None)
		
if isinstance(IN[0], list): OUT = refArr,locationPoint
else: OUT = refArr[0],locationPoint[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b3547d79-9204-4a72-917f-a1e8e2598b12" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="780" y="316.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="99d9e9f6-3779-446f-90cd-dec00223f28a" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="588.8" y="269.826666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7d3ac5db-f406-44c0-a98e-ecff5325141e" start_index="0" end="aea22160-5352-44e1-b28e-f7f1aa6fdc90" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aea22160-5352-44e1-b28e-f7f1aa6fdc90" start_index="0" end="99d9e9f6-3779-446f-90cd-dec00223f28a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="99d9e9f6-3779-446f-90cd-dec00223f28a" start_index="0" end="6c504b73-f7b8-4b18-b8c8-510f4ad83193" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="99d9e9f6-3779-446f-90cd-dec00223f28a" start_index="1" end="b3547d79-9204-4a72-917f-a1e8e2598b12" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>