<Workspace Version="1.3.4.6666" X="131.55390897402" Y="102.497788017005" zoom="0.679007436100058" ScaleFactor="1" Name="Family Get SubCategory" Description="Retrieves the subcategories for a given family or family instance." ID="47ea519a-0a4c-4709-b30f-00ec86145ca8" Category="GeniusLoci.Family">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="17681039-24c9-484c-b342-d37d77c883a3" type="PythonNodeModels.PythonNode" nickname="Family Get SubCategory" x="260.744939168416" y="226.762795363281" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Alban de Chasteigner 2019
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

families = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
fCat,subCategory = [],[]

TransactionManager.Instance.ForceCloseTransaction()
for fam in families:
	if isinstance(fam,FamilyInstance):
		family=fam.Symbol.Family
		famDoc = doc.EditFamily(family)
		cate=Revit.Elements.Category.ById((family.FamilyCategoryId).IntegerValue)
	elif isinstance(fam,Family):
		if fam.IsInPlace ==False:
			family=fam
		famDoc = doc.EditFamily(family)
		cate=Revit.Elements.Category.ById((family.FamilyCategoryId).IntegerValue)
	#elif isinstance(fam,Document):
		#famDoc = fam
		#cate=Revit.Elements.Category.ById((famDoc.OwnerFamily.FamilyCategoryId).IntegerValue)
	else: pass	
	category = famDoc.OwnerFamily.FamilyCategory
	subcat=category.SubCategories
	for i in subcat:
		try:
			subCategory.append(Revit.Elements.Category.ById(i.Id.IntegerValue))
		except:subCategory.append(None)
	fCat.append(cate)
	if not isinstance(fam,Document):
		famDoc.Close(False)
	
if isinstance(IN[0], list): OUT = fCat,subCategory
else: OUT = fCat[0],subCategory</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e025644b-02f3-416c-9ca0-f8447fc49306" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-31.9371812156014" y="226.997164946013" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FamilyOrFamilyInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="28b238da-9123-4341-80db-2a34fe8f5813" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="684.046561416204" y="191.193081355843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="470fce16-f032-4bd4-b239-c9d06b3ed9fb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="684.046561416204" y="275.193081355843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="SubCategory" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d5694968-6aaf-431b-9191-187c666ff1c9" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="492.846561416204" y="228.619748022509" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="17681039-24c9-484c-b342-d37d77c883a3" start_index="0" end="d5694968-6aaf-431b-9191-187c666ff1c9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e025644b-02f3-416c-9ca0-f8447fc49306" start_index="0" end="17681039-24c9-484c-b342-d37d77c883a3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5694968-6aaf-431b-9191-187c666ff1c9" start_index="0" end="28b238da-9123-4341-80db-2a34fe8f5813" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d5694968-6aaf-431b-9191-187c666ff1c9" start_index="1" end="470fce16-f032-4bd4-b239-c9d06b3ed9fb" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>