<Workspace Version="1.3.4.6666" X="135.265928653125" Y="89.1745874227433" zoom="0.747692817123325" ScaleFactor="1" Name="FamilyInstance Reference ByName" Description="Works only in Revit 2018.1 and later.&#xD;&#xA;Gets the reference corresponding to the named reference plane in the instance's family. " ID="3ec17443-ffb8-4bb9-a2b7-ec106b4f7a82" Category="GeniusLoci.Reference">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5c9dc7a0-6c8c-41fd-872e-6c5a01a7f2be" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-41.1993728901578" y="294.021482549247" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="familyInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="a73228d8-16dd-414e-8a0e-ef6d5c663c36" type="PythonNodeModels.PythonNode" nickname="Python Script" x="378.800627109842" y="323.021482549247" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Alban de Chasteigner 2019
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

elements = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
names = IN[1] if isinstance(IN[1],list) else [IN[1]]	
references, planeList = [],[]

for elem in elements:
	for name in names:
		reference=elem.GetReferenceByName(name)
		references.append(reference)
		try :
			TransactionManager.Instance.EnsureInTransaction(doc)
			trans1 = SubTransaction(doc)
			trans1.Start()
			sketch=SketchPlane.Create(doc,reference)
			plane = sketch.GetPlane().ToPlane(True)
			sketch.Dispose()
			trans1.RollBack()
			TransactionManager.Instance.TransactionTaskDone()
		except :
			plane=None
		planeList.append(plane)
		
if not isinstance(IN[0], list) and not isinstance(IN[1], list): OUT = references[0],planeList[0]
else: OUT = references,planeList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="bbcf049d-503d-4dd9-a7ee-1619377a0a51" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="794.800627109842" y="289.808149215914" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Reference" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4dddfeab-9c05-4b07-b50d-e5c72e84b745" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-41.1993728901578" y="378.021482549247" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Reference Plane Name&#xD;&#xA;name : string=&quot;Center (Left/Right)&quot;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0a8711c4-7a35-48d0-a68f-452fa15ad060" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="603.600627109842" y="327.23481588258" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c5d86494-e4c4-4ea2-8d82-572dfa708f07" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="794.800627109842" y="373.808149215914" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Plane" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5c9dc7a0-6c8c-41fd-872e-6c5a01a7f2be" start_index="0" end="a73228d8-16dd-414e-8a0e-ef6d5c663c36" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a73228d8-16dd-414e-8a0e-ef6d5c663c36" start_index="0" end="0a8711c4-7a35-48d0-a68f-452fa15ad060" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4dddfeab-9c05-4b07-b50d-e5c72e84b745" start_index="0" end="a73228d8-16dd-414e-8a0e-ef6d5c663c36" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0a8711c4-7a35-48d0-a68f-452fa15ad060" start_index="0" end="bbcf049d-503d-4dd9-a7ee-1619377a0a51" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0a8711c4-7a35-48d0-a68f-452fa15ad060" start_index="1" end="c5d86494-e4c4-4ea2-8d82-572dfa708f07" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>