<Workspace Version="1.3.4.6666" X="-99.8394743545995" Y="120.019459591988" zoom="0.70823125" ScaleFactor="1" Name="Get Flipped Element" Description="Gets the flipped wall, hand flipped (hinge side) and facing flipped (interior wall side) doors." ID="13d56b38-1333-40e7-a286-f25e1aaeb1d8" Category="GeniusLoci.Element">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d6f8c5cb-7071-471a-a226-23afe83270e5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="411.8" y="289.213333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import Element

elements = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]

flippedElements,items = [],[]

for element in elements:
	if hasattr(element, "Flipped"):
		if element.Flipped is True:
			flippedElements.append(element)
		else:
			items.append(element)
	elif hasattr(element, "HandFlipped"):
		if element.HandFlipped is True:
			flippedElements.append(element)
		else:
			items.append(element)
	elif hasattr(element, "FacingFlipped"):
		if element.FacingFlipped is True:
			flippedElements.append(element)
		else:
			items.append(element)
OUT = flippedElements, items</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="96c38f2d-911d-499a-a2a4-7d7ba36e2d11" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="223.4" y="289.213333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="63a1d2c2-5322-48dc-aef4-a701236bf887" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="636.2" y="293.426666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2c70cc71-b608-405d-8ae9-f2093b0cf472" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="827.4" y="256" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Flipped element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ef8bc7b0-1297-4ac7-a84d-b2c51cd92a88" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="827.4" y="340" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="other element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d6f8c5cb-7071-471a-a226-23afe83270e5" start_index="0" end="63a1d2c2-5322-48dc-aef4-a701236bf887" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96c38f2d-911d-499a-a2a4-7d7ba36e2d11" start_index="0" end="d6f8c5cb-7071-471a-a226-23afe83270e5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="63a1d2c2-5322-48dc-aef4-a701236bf887" start_index="0" end="2c70cc71-b608-405d-8ae9-f2093b0cf472" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="63a1d2c2-5322-48dc-aef4-a701236bf887" start_index="1" end="ef8bc7b0-1297-4ac7-a84d-b2c51cd92a88" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>