<Workspace Version="1.3.4.6666" X="55.9028925" Y="89.9814825" zoom="0.70823125" ScaleFactor="1" Name="OpenWorksets Enumeration" Description="Enumerates the set of user-created worksets to open in memory. For use with the Document SaveAs node." ID="8bca20ee-3169-4863-a11c-b2626328f959" Category="GeniusLoci.Workset">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="66012a1d-eb70-4944-8bcf-965968e608fa" type="PythonNodeModels.PythonNode" nickname="Python Script" x="457.6" y="281.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import SimpleWorksetConfiguration
import System

OUT = System.Enum.GetValues(Autodesk.Revit.DB.SimpleWorksetConfiguration)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="007dcfdf-acdc-4d1c-b5b3-523c0e441348" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="598.246840279923" y="280.725423369839" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="WorksetConfiguration" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="66012a1d-eb70-4944-8bcf-965968e608fa" start_index="0" end="007dcfdf-acdc-4d1c-b5b3-523c0e441348" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>