<Workspace Version="1.3.4.6666" X="170.264447556343" Y="135.991652896402" zoom="0.593767140625" ScaleFactor="1" Name="Print Settings ByName" Description="Collect printsettings by given name in the active or given document." ID="647925ff-f433-4897-94b1-5a801c70f927" Category="GeniusLoci.Printing">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="9d514d93-6c95-41ad-8f47-bae163436116" type="PythonNodeModels.PythonNode" nickname="Python Script" x="286.4" y="215.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import FilteredElementCollector, PrintSetting

# Part of script from Clockwork
inputdoc = UnwrapElement(IN[1])
if inputdoc == None:
	doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
	doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
	doc = inputdoc
else: 
	doc = DocumentManager.Instance.CurrentDBDocument

names = IN[0] if isinstance(IN[0],list) else [IN[0]]
outList = []

printSet = {}
printSettings = FilteredElementCollector(doc).OfClass(PrintSetting)
for ps in printSettings:
	printSet[ps.Name] = ps

for name in names:
	for key in printSet.keys():
		if key == name:
			outList.append(printSet[name])
			break

if isinstance(IN[0], list): OUT = outList
else: OUT = outList[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9ef2d6df-c15d-4956-a774-fb2fb5d1fa08" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="24.8" y="163.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//String&#xD;&#xA;printSettingsName" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9f02bfe2-df8a-4f21-98a0-bd6d8fe39cc4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-216" y="268" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c7a3ce67-1c31-413d-90ff-4d51e6ff8e59" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="464" y="224" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="PrintSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9d514d93-6c95-41ad-8f47-bae163436116" start_index="0" end="c7a3ce67-1c31-413d-90ff-4d51e6ff8e59" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9ef2d6df-c15d-4956-a774-fb2fb5d1fa08" start_index="0" end="9d514d93-6c95-41ad-8f47-bae163436116" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f02bfe2-df8a-4f21-98a0-bd6d8fe39cc4" start_index="0" end="9d514d93-6c95-41ad-8f47-bae163436116" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>