<Workspace Version="1.3.4.6666" X="-76.4726426089278" Y="72.1008647309479" zoom="0.784369328044827" ScaleFactor="1" Name="Reset SystemType Graphics" Description="Clear the line pattern, line weight, line color and  material of the given System Type." ID="2800efe7-b9f6-4b3c-b4f8-8f1ab4b08cb3" Category="GeniusLoci.MEP">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="181aa3ec-c6ec-4cf7-978a-5c549f993f39" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="296.8" y="304.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="SystemType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d17719d0-56f3-4647-94d8-8d95d7ab7e32" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="695.202892239852" y="302.320289223985" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="SystemType" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="2e952c20-d39f-40ae-95a8-3b2f0c633ee9" type="PythonNodeModels.PythonNode" nickname="Reset SystemType Properties" x="455.490328133419" y="302.789931703549" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

def tolist(obj1):
    if hasattr(obj1,"__iter__"): return obj1
    else: return [obj1]

doc = DocumentManager.Instance.CurrentDBDocument
systypes = tolist(UnwrapElement(IN[0]))

TransactionManager.Instance.EnsureInTransaction(doc)
for systype in systypes:
	systype.LineColor = Autodesk.Revit.DB.Color.InvalidColorValue
	systype.LineWeight = -1
	systype.LinePatternId = ElementId.InvalidElementId
	systype.MaterialId = ElementId.InvalidElementId
TransactionManager.Instance.TransactionTaskDone()

OUT = systypes</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="181aa3ec-c6ec-4cf7-978a-5c549f993f39" start_index="0" end="2e952c20-d39f-40ae-95a8-3b2f0c633ee9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2e952c20-d39f-40ae-95a8-3b2f0c633ee9" start_index="0" end="d17719d0-56f3-4647-94d8-8d95d7ab7e32" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>