<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="RevitLinkInstance ByPoint" Description="Link the Revit Instance to the given point. The input &quot;Rotation&quot; is optional." ID="50415179-272c-4951-8aed-9479f9c06572" Category="GeniusLoci.Import">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="193842af-16e3-476e-8a50-3604981263ff" type="PythonNodeModels.PythonNode" nickname="Python Script" x="319.2" y="276" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

import math

links = UnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]
links = links[0]
locations = IN[1] if isinstance(IN[1],list) else [IN[1]]
rotations = IN[2] if isinstance(IN[2],list) else [IN[2]]
instances, points = [], []
	
TransactionManager.Instance.EnsureInTransaction(doc)
for loc in locations:
	xyz=loc.ToXyz()
	points.append(xyz)
	linkInstance = RevitLinkInstance.Create(doc,links.Id,ImportPlacement.Origin)
	linkInstance.Location.Move(xyz)
	if rotations[0] == None:
		pass	
	else:
		axis = Line.CreateBound(xyz, XYZ(xyz.X,xyz.Y,xyz.Z +1))
		ElementTransformUtils.RotateElement(doc,linkInstance.Id,axis,rotations[points.index(xyz)]*math.pi/-180)
	instances.append(linkInstance)
TransactionManager.Instance.TransactionTaskDone()
	
OUT = instances</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c61019b8-6397-4edb-a036-7a3fc9abf624" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="129.6" y="260" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="revitLinkType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e359c2f9-d6b5-4cc0-a2f0-714a20ee20a4" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="497.6" y="281.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="RevitLinkInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1db8cf35-8d75-4852-8f4a-ec81208d39a5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-181.6" y="326.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Point where the instance is to be placed&#xD;&#xA;location:Autodesk.DesignScript.Geometry.Point[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="993f3d27-8900-41d8-97fc-157ef26fd7f2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="40.3999999999999" y="416.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Optional input&#xD;&#xA;rotation:var[]..[]=null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="193842af-16e3-476e-8a50-3604981263ff" start_index="0" end="e359c2f9-d6b5-4cc0-a2f0-714a20ee20a4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c61019b8-6397-4edb-a036-7a3fc9abf624" start_index="0" end="193842af-16e3-476e-8a50-3604981263ff" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1db8cf35-8d75-4852-8f4a-ec81208d39a5" start_index="0" end="193842af-16e3-476e-8a50-3604981263ff" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="993f3d27-8900-41d8-97fc-157ef26fd7f2" start_index="0" end="193842af-16e3-476e-8a50-3604981263ff" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>