<Workspace Version="1.3.4.6666" X="-21.0783634344014" Y="56.6420528605152" zoom="0.658674852158215" ScaleFactor="1" Name="View ByType" Description="Gets all views by type.&#xD;&#xA;For the View Template Type, the 3D View Templates will not be retrieved." ID="b9b43409-2fe0-40de-bbdc-e632ebd588be" Category="GeniusLoci.View">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="848f8c9b-ddd3-418b-b4bb-97a8484400d6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="97.1771415884019" y="207.808077138726" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//For use with the View Type or the ViewFamilyTypes nodes&#xD;&#xA;//String or ViewFamilyType&#xD;&#xA;viewType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="252db1a1-9687-4473-9520-a000d61fac8f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="224.907794667113" y="321.424945565726" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Use only to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var[]..[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="05af9133-9a3d-4b3f-be27-ebc75d9fadbe" type="PythonNodeModels.PythonNode" nickname="Python Script" x="662.6" y="241.436717062635" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Inspired by archilab
import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager

import System

viewType = UnwrapElement(IN[0])
inputdocs = UnwrapElement(IN[1]) if isinstance(IN[1],list) else [UnwrapElement(IN[1])]

for inputdoc in inputdocs :
	if inputdoc == None:
		doc = DocumentManager.Instance.CurrentDBDocument
	elif isinstance (inputdoc, Document) :
		doc = inputdoc
	elif isinstance (inputdoc, RevitLinkInstance) :
		doc = inputdoc.GetLinkDocument()
	else: doc = DocumentManager.Instance.CurrentDBDocument

viewList=[]
colViews = FilteredElementCollector(doc).OfClass(View).ToElements()

for v in colViews:
	if viewType != "View Template" and isinstance(viewType,basestring) :
		vType  = System.Enum.Parse(Autodesk.Revit.DB.ViewType, IN[0])
		#fType  = (doc.GetElement(v.GetTypeId())).get_Parameter(BuiltInParameter.ALL_MODEL_TYPE_NAME).AsString()
		if v.ViewType == vType and not v.IsTemplate:
			viewList.Add(v)
	elif isinstance(viewType,ViewFamilyType) :
		if v.GetTypeId() == viewType.Id:
			viewList.Add(v)
	elif viewType == "View Template":
		if v.ViewType != ViewType.ThreeD and v.IsTemplate:
			viewList.Add(v)

OUT=viewList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0862ba9a-0cde-4ea2-b24c-92125fd78810" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="887" y="241.436717062635" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="848f8c9b-ddd3-418b-b4bb-97a8484400d6" start_index="0" end="05af9133-9a3d-4b3f-be27-ebc75d9fadbe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="252db1a1-9687-4473-9520-a000d61fac8f" start_index="0" end="05af9133-9a3d-4b3f-be27-ebc75d9fadbe" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="05af9133-9a3d-4b3f-be27-ebc75d9fadbe" start_index="0" end="0862ba9a-0cde-4ea2-b24c-92125fd78810" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>