<Workspace Version="1.3.4.6666" X="0" Y="0" zoom="1" ScaleFactor="1" Name="View ResetCropBox" Description="Removes any non-rectangular boundary of the view's cropbox. " ID="87d8f28a-a32c-4b85-82b7-f05848609a0f" Category="GeniusLoci.View">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="a42c7005-00e9-4bca-8f05-866d31201901" type="PythonNodeModels.PythonNode" nickname="Python Script" x="424" y="342.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#solamour on https://forum.dynamobim.com/t/how-to-reset-crop-view-using-dynamo/25140/5

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import View

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

views = UUnwrapElement(IN[0]) if isinstance(IN[0],list) else [UnwrapElement(IN[0])]

TransactionManager.Instance.EnsureInTransaction(doc)
for v in views:
	if v.CropBoxActive == True:
		csm = v.GetCropRegionShapeManager()
		csm.RemoveCropRegionShape()
TransactionManager.Instance.TransactionTaskDone()

if isinstance(IN[0], list): OUT = views
else: OUT = views[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b5a7dfe3-39e9-40e0-a3e5-abfe4a62bb7c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="298.8" y="338.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2cb61cf2-7cc4-4132-8871-52f1b4c05556" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="600" y="345.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="View" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a42c7005-00e9-4bca-8f05-866d31201901" start_index="0" end="2cb61cf2-7cc4-4132-8871-52f1b4c05556" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b5a7dfe3-39e9-40e0-a3e5-abfe4a62bb7c" start_index="0" end="a42c7005-00e9-4bca-8f05-866d31201901" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>