<Workspace Version="1.3.4.6666" X="-62.1898620152197" Y="-63.8396456113217" zoom="0.729950825270786" ScaleFactor="1" Name="View ByName" Description="Collect views by given name in the active or given document.&#xD;&#xA;Based on a Christian Gartland's script." ID="4ca81f03-d333-46ac-ac82-f863416c768d" Category="GeniusLoci.View">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="08380198-d94d-461d-8c42-e9ac01a090d1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="186.130577991007" y="377.438638948575" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ViewName" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="70f22556-b881-4e8d-9e0a-020174ec971c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="186.130577991007" y="460.438638948575" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="DoesContain:bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="82174356-f03e-474d-bccd-2ebc5e07fc83" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="928.530577991007" y="434.438638948575" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="ec9ca173-eefa-4883-825d-e057b61e28f1" type="PythonNodeModels.PythonNode" nickname="Get View By Name" x="703.730577991007" y="434.438638948575" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Inspired by cgartland
import clr
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import FilteredElementCollector, View, ViewType
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

# inputdoc from Clockwork
inputdoc = UnwrapElement(IN[2])
if inputdoc == None:
	doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
	doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
	doc = inputdoc
else: 
	doc = None

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]

names = tolist(IN[0])
cont = tolist(IN[1])
cont = cont[0]
outList = []

#ueWrapper from Dimitar Venkov
ueWrapper = None
wrappers = clr.GetClrType(Revit.Elements.ElementWrapper).GetMethods()
for w in wrappers:
	if w.ToString().startswith("Revit.Elements.UnknownElement"):
		ueWrapper = w
		break

views = {}
views_all = FilteredElementCollector(doc).OfClass(View)
# Create a dictionary associating Names to Views
# e.g. {'3D View 1': View3D}
for view in views_all:
	#if not view.IsTemplate:
	views[view.Name] = view

for name in names:
	for key in views.keys():
		if cont:
			if name in key :
				if views[key].IsTemplate and views[key].ViewType == ViewType.ThreeD :
					outList.append(ueWrapper.Invoke(None,(views[key], True)))
				else: outList.append(views[key])
		else:
			if key == name:
				if views[key].IsTemplate and views[key].ViewType == ViewType.ThreeD :
					outList.append(ueWrapper.Invoke(None,(views[key], True)))
				else: outList.append(views[key])
				break

if len(outList)&gt;1 : OUT = outList
else: OUT = outList[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6b59b49b-7ecc-4194-a7c6-373dba36eab0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="186.130577991007" y="543.438638948575" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="08380198-d94d-461d-8c42-e9ac01a090d1" start_index="0" end="ec9ca173-eefa-4883-825d-e057b61e28f1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="70f22556-b881-4e8d-9e0a-020174ec971c" start_index="0" end="ec9ca173-eefa-4883-825d-e057b61e28f1" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ec9ca173-eefa-4883-825d-e057b61e28f1" start_index="0" end="82174356-f03e-474d-bccd-2ebc5e07fc83" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6b59b49b-7ecc-4194-a7c6-373dba36eab0" start_index="0" end="ec9ca173-eefa-4883-825d-e057b61e28f1" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>